spring:
  flyway:
    enabled: true
    table: schema_version_ai
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
    validate-on-migrate: true
    placeholder-prefix: "#{"
    ignore-migration-patterns: "*:missing"
  datasource:
    hikari:
      maximum-pool-size: 16
      max-lifetime: 3600000
  data:
    redis: #redis
      host: ${spring.redis.host:10.70.70.85}
      port: ${spring.redis.port:16379}
      password: ${spring.redis.password:yz2D&6gNK7}
      database: ${spring.redis.database:6}
      timeout: ${spring.redis.timeout:10000}
server:
  servlet:
    context-path: /flex-ai
    session:
      cookie:
        name: ailpha-bigdata
        path: /
  port: 8902
  tomcat:
    uri-encoding: UTF-8


ailpha:
  datasource:
    type: postgresql
    jdbc-url: jdbc:postgresql://${ailpha.default.pg.host:10.70.70.85}:${ailpha.default.pg.host:5432}/ailpha?currentSchema=ai&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${ailpha.default.pg.username:dbapp}
    password: ${ailpha.default.pg.password:jY%kng8cc&}
    driver-class-name: org.postgresql.Driver
  flexsdk:
    app: zq
    es-config:
      version: 7.17.14


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.dbapp.*.model

xxl:
  job:
    admin:
      addresses: http://${flex.job.service.host:127.0.0.1:8080}/xxl-job-admin
    executor:
      appname: flex-job-executor-ai
      log-path: logs/job-handler
      log-retention-days: 7